# Generated by Django 6.0.2 on 2026-02-21 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日期')),
                ('target_calories', models.PositiveIntegerField(verbose_name='当天目标总热量(kcal)')),
                ('recipes', models.ManyToManyField(blank=True, related_name='diet_plans', to='recipes.recipe', verbose_name='食谱')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '饮食计划',
                'verbose_name_plural': '饮食计划',
                'db_table': 'diet_plan',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
