# Generated by Django 6.0.2 on 2026-02-21 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet_planner', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '加餐')], max_length=20, verbose_name='餐次')),
                ('portion', models.FloatField(default=1.0, verbose_name='份数')),
                ('diet_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='diet_planner.dietplan', verbose_name='饮食计划')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plan_items', to='recipes.recipe', verbose_name='食谱')),
            ],
            options={
                'verbose_name': '饮食计划条目',
                'verbose_name_plural': '饮食计划条目',
                'db_table': 'diet_plan_item',
            },
        ),
        migrations.RemoveField(
            model_name='dietplan',
            name='recipes',
        ),
        migrations.AddField(
            model_name='dietplan',
            name='recipes',
            field=models.ManyToManyField(blank=True, related_name='diet_plans', through='diet_planner.DietPlanItem', to='recipes.recipe', verbose_name='食谱'),
        ),
    ]
