# Generated by Django 6.0.2 on 2026-02-21 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='食谱名称')),
                ('calories', models.PositiveIntegerField(verbose_name='卡路里')),
                ('protein', models.FloatField(verbose_name='蛋白质')),
                ('carbs', models.FloatField(verbose_name='碳水')),
                ('fats', models.FloatField(verbose_name='脂肪')),
                ('ingredients', models.TextField(verbose_name='食材清单')),
                ('instructions', models.TextField(verbose_name='制作步骤')),
            ],
        ),
    ]
